# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.kernel.sysctl = {
    "vm.swappiness" = lib.mkDefault 1;
  };

  services.fstrim.enable = lib.mkDefault true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1bcbd860-d90b-4140-a2c0-11cca9ea38b0";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" "nodiratime" "discard" ];
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/df76c839-cd2a-4097-895a-066d4654bfeb";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1bcbd860-d90b-4140-a2c0-11cca9ea38b0";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" "nodiratime" "discard" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1bcbd860-d90b-4140-a2c0-11cca9ea38b0";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" "nodiratime" "discard" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/1bcbd860-d90b-4140-a2c0-11cca9ea38b0";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd" "noatime" "nodiratime" "discard" ];
      neededForBoot = true;
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/1bcbd860-d90b-4140-a2c0-11cca9ea38b0";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress=zstd" "noatime" "nodiratime" "discard" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7713-7A09";
      fsType = "vfat";
    };

  fileSystems."/mnt" =
    { device = "/dev/disk/by-uuid/1bcbd860-d90b-4140-a2c0-11cca9ea38b0";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9dcd98a0-0a3d-4bb1-97af-e56714a65235"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
